### ISSUE TITLE
How does it work with @fastify/autoload ?

### ISSUE THREAD

**Issue by ManUtopiK** [Vanilla-IceCream/vite-plugin-fastify#1]
Hi !
I built a boilerplate here https://github.com/ManUtopiK/vite-fastify-boilerplate with [vite-plugin-node](https://github.com/axe-me/vite-plugin-node).

I get an issue with fastify-autoload here https://github.com/ManUtopiK/vite-fastify-boilerplate/issues/7
I took a try fast with your plugin and it seems fastify-autoload doesn't work also.

Do you know a workarround for this ?
Also, I didn't test but do you know if your plugin works with websocket ?

**Comment by Shyam-Chen** [comment]
The `@fastify/autoload` is currently unavailable. You may want to consider using `vite-plugin-fastify-routes` instead.

If you want to use WebSocket, you need to switch the development server from `vite` to `vite-node`.
